name: test_minpro_insta
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  cloud_firestore: ^4.4.3

  cupertino_icons: ^1.0.2

  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.0
  intl: ^0.18.0
  provider: ^6.0.5

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
